### ISSUE TITLE
[RFC] 에러 메시지 정의

### ISSUE THREAD

**Issue by hyunjinee** [team-yaza/mozi-server#45]
## 🌴 **상태 코드 + 우리 어플리케이션의 에러 메시지 정의**

![image](https://user-images.githubusercontent.com/63354527/181914673-a36cde3f-df00-4f3a-927d-d0c2dbdfda0d.png)

## 📚 참고자료

https://tecoble.techcourse.co.kr/post/2021-08-13-react-error-handling/

**Comment by sion-k** [comment]
에러 메시지를 정의해서 문서를 작성한 뒤에 json에 message를 같이 보내는 식으로 구성하면 좋을 것 같습니다

**Comment by hyunjinee** [comment]
조아요조아요
