### ISSUE TITLE
husky setting

### ISSUE THREAD

**Issue by hyunjinee** [team-yaza/mozi-server#7]
## 🌴 **husky 설정**

CI를 위해 husky를 설정합니다. 

husky는 개발환경에서 git hooks를 손쉽게 제어하도록 도와주는 라이브러리입니다.
git에 대한 특정 이벤트가 발생했을 때, 특정 스크립트가 실행되도록 도와줍니다.
git hooks를 제어하는 것에 해당 라이브러리를 도입한 이유는 원격에서 공유되어야 하는 프로젝트이기 때문입니다.
.git 디렉터리에 저장되는 경우 원격으로 저장하고 관리하기 어려워 해당 라이브러리를 도입합니다.
lint-staged는 변경된 파일만 린트를 적용하고 테스트하기 위해 도입합니다.

## 📋 **태스크 리스트**

- [x] prettier, eslint, husky 의존성 추가

## 📚 참고자료

[YAZA 노션](https://roomy-phone-06d.notion.site/Team-Yaza-92625391b533460fb797bbce9f8839df)

**Comment by HanCiHu** [comment]
프론트엔드에서 허스키에 대해 이야기 해보았습니다. 서버도 동일하게 진행하면 좋을 것 같아요 :)
